### ISSUE TITLE
Test getLength()

### ISSUE THREAD

**Issue by abdomody35** [abdomody35/object-oriented-programming-1#9]
Testing the getLength function for String class is needed

**Comment by vvu11** [comment]
Hi @abdomody35 just wondering what you mean by this to see if there is any way I can help

**Comment by abdomody35** [comment]
Hello, @vvu11 

For testing any function in this repo you should : 

1) Choose a C++ unit testing framework like [catch](https://github.com/catchorg/Catch2), [googletest](https://github.com/google/googletest), [doctest](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C++) or [anything from here](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C++)
2) lookup how to write tests in the framework you chose
3) Write test cases for the getLength() function (for this issue) or any function you choose that cover all possible scenarios, including positive and negative scenarios, edge cases, and error conditions.
